# Generated by Django 4.2.9 on 2024-01-29 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_name', models.CharField(max_length=20)),
                ('stu_age', models.IntegerField()),
                ('stu_dob', models.DateTimeField()),
                ('stu_mob', models.IntegerField()),
                ('stu_subject', models.CharField(max_length=20)),
                ('stu_marks', models.IntegerField()),
                ('stu_rank', models.IntegerField()),
                ('stu_collage', models.CharField(max_length=20)),
                ('stu_addmisson_date', models.DateField()),
            ],
        ),
    ]
