# Generated by Django 4.2.9 on 2024-01-29 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ORM', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student_data',
            options={'verbose_name': 'STUDENT DATA'},
        ),
        migrations.AlterField(
            model_name='student_data',
            name='stu_mob',
            field=models.BigIntegerField(),
        ),
    ]
